# Generated by Django 5.0.7 on 2024-12-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='method',
        ),
    ]
